settings:
  type: "ssh"
  ssh_user: "isard"
  ssh_timeout: 5
  max_threads: 10
  disable_time: 20
  version: "1.0.0"
  directory:
    data: "/tmp"
    binary: "/usr/local/bin"
    settings: "/etc/sentinella"

buttons:
  - title: "Chromium"
    unique_word: "chromium"
    style: "success"
    command: "DISPLAY=:0 nohup /usr/local/bin/start-chromium-kiosk.sh  >/dev/null 2>&1 &"
    
  - title: "Desactiva internet"
    unique_word: "disable"
    style: "warning"
    command: "touch /tmp/sentinella"

  - title: "Activa internet"
    unique_word: "enable"
    style: "success"
    command: "rm --force /tmp/sentinella"

  - title: "Comprova Google"
    unique_word: "google"
    style: "info"
    command: "ping -c 4 www.google.com"

  - title: "Comprova usuaris"
    unique_word: "usuaris"
    style: "info"
    command: "who | awk '{print $1}'"
 
