settings:
  type: "ssh"
  ssh_user: "isard"
  ssh_timeout: 5
  max_threads: 10
  version: "1.0.0"
  directory:
    data: "/tmp"
    binary: "/usr/local/bin"
    settings: "/etc/sentinella"

buttons:
  - title: "Desactiva internet"
    unique_word: "disable"
    color: "#FFFFFF"
    background_color: "#007BFF"
    command: "touch /tmp/sentinella"

  - title: "Activa internet"
    unique_word: "enable"
    color: "#FFFFFF"
    background_color: "#007BFF"
    command: "rm --force /tmp/sentinella"

  - title: "Comprova internet"
    unique_word: "enable"
    color: "#FFFFFF"
    background_color: "#007BFF"
    command: "sudo ufw verbose"
    
  - title: "Inicia el navegador"
    unique_word: "start"
    color: "#FFFFFF"
    background_color: "#007BFF"
    command: "start-chromium-kiosk.sh"