settings:
  type: "ssh"
  ssh_user: "isard"
  ssh_timeout: 5
  max_threads: 10
  disable_time: 20
  version: "1.0.0"
  directory:
    data: "/tmp"
    binary: "/usr/local/bin"
    settings: "/etc/sentinella"

buttons:
  - title: "Inst. Browser policies"
    unique_word: "chromium"
    style: "success"
    command: "touch /tmp/sentinella_browser"

  - title: "Desint. Browser policies"
    unique_word: "chromium-desactiva"
    style: "warning"
    command: "rm --force /tmp/sentinella_browser"

  - title: "Restringeix internet"
    unique_word: "disable"
    style: "success"
    command: "touch /tmp/sentinella_internet"

  - title: "Permet internet"
    unique_word: "enable"
    style: "warning"
    command: "rm --force /tmp/sentinella_internet"

  - title: "Grava"
    unique_word: "start-recording"
    style: "success"
    command: "touch /tmp/sentinella-record"
  - title: "Para gravació"
    unique_word: "stop-recording"
    style: "warning"
    command: "rm --force /tmp/sentinella-record"

  - title: "Comprova Google"
    unique_word: "google"
    style: "info"
    command: "ping -c 4 www.google.com"

  - title: "Comprova usuaris"
    unique_word: "usuaris"
    style: "info"
    command: "who | awk '{print $1}'"

